/*global console, process, require*/
( function () {
    'use strict';
	let mongo = require( 'mongoose' );
	mongo.connect( 'mongodb://localhost/webstrate-pi' );
	let ApiServer = require('./modules/apiServer/apiServer.js');
	let DeviceScanner = require('./modules/deviceScanner/deviceScanner.js');
	
	process.title = 'webstrate-pi';
	
    let fs = require( 'fs' );

    let config;
    let server, scanner, phantomjs;

    fs.readFile( 'config/autogenerated.config', 'utf8', function ( err, data ) {
        try {
            if ( err ) {
                throw err;
            }
            config = JSON.parse( data );
        } catch ( e ) {
            console.error( err );
            process.exit( 1 );
        }
        if ( config ) {
			console.log(config);
			server = new ApiServer( config );
			scanner = new DeviceScanner(config);
			
        }
    } );
}() );
