#!/bin/bash
# /etc/init.d/webstrate-pi

### BEGIN INIT INFO
# Provides:          webstrate-pi
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: webstrate-pi init script
# Description:       This service is used to manage webstrate-pi at startup etc.
### END INIT INFO