#!/bin/bash
# /etc/init.d/webstrate-pi

### BEGIN INIT INFO
# Provides:          webstrate-pi
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: webstrate-pi init script
# Description:       This service is used to manage webstrate-pi at startup etc.
### END INIT INFO
path=/home/pi/webstrate-pi
case "$1" in
    start)
        echo "Starting webstrate-pi service"
		echo "starting webstrate-pi service" > /var/log/webstrate-pi/webstrate-pi.log
		${path}/scripts/start.sh ${path} > /var/log/webstrate-pi/logs.log 2> /var/log/webstrate-pi/errors.log
        ;;
    stop)
        echo "Stopping webstrate-pi service"
		echo "Stopping webstrate-pi service" > /var/log/webstrate-pi/logs.log
        killall webstrate-pi
        ;;
    *)
        echo "Usage: /etc/init.d/webstrate-pi start|stop"
        exit 1
        ;;
esac

exit 0
